# Generated by Django 5.2.7 on 2025-11-21 17:45

import django_resized.forms
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cred',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sfname', models.CharField(max_length=100)),
                ('smname', models.CharField(blank=True, max_length=200, null=True)),
                ('slname', models.CharField(max_length=100)),
                ('gfname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gend', models.CharField(max_length=10)),
                ('gc_no', models.BigIntegerField()),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('addr', models.TextField()),
                ('prog', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('cls_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=student.models.rename_student_photo)),
            ],
        ),
    ]
