# Generated by Django 5.2.8 on 2025-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssname', models.CharField(max_length=50)),
                ('slname', models.CharField(max_length=200)),
                ('gfname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('ph_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('addr', models.CharField(max_length=400)),
                ('cls_name', models.CharField(max_length=100, null=True)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
