# Generated by Django 5.2.7 on 2025-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rdesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
