# Generated by Django 5.2.8 on 2025-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email_alter_student_ph_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='del_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ph_no', models.BigIntegerField()),
            ],
        ),
    ]
