# Generated by Django 5.2.7 on 2025-11-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_rdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('details', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
