# Generated by Django 5.2.7 on 2025-11-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_del_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rdesc',
        ),
    ]
