# Generated by Django 5.2.7 on 2025-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('tname', models.CharField(max_length=200)),
                ('dur', models.IntegerField()),
                ('desc1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200, unique=True)),
                ('dur', models.IntegerField()),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
